title: Kjetil Andresen
email: kjetil.andrese@gmail.com
author_name: "Kjetil Andresen"
logo_url: https://avatars.githubusercontent.com/u/4138151?v=4
description: >-
  Jazz, programming and vinyl.
github_username: kjetand
sass:
  style: compressed

remote_theme: heiswayi/the-plain

# Site Settings
timezone: Europe/Oslo
mathjax: false

# Site Build
highlighter: rouge
future: true

# Other Params
exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: "null"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
